# Site settings
title: 42Technical
email: scott@42technical.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 42Technical | Scott Hammond

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/wookieneck
  - title: facebook
    url: https://www.facebook.com/wookieneck?fref=ts
  - title: stack-overflow
    url:
  - title: linkedin
    url: https://www.linkedin.com/in/scott-hammond-62ab629
  - title: github
    url: https://github.com/joecacti/joecacti.github.io

# Build settings
markdown: kramdown
permalink: pretty
